name: Training on EC2 selfhosted Runner
on: [push, pull_request]

jobs:
  deploy-runner: # (1) Deployment of the EC2 runner 
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Runner deployment on EC2
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          cml runner \
              --cloud=aws \
              --cloud-region=us-east-1a \
              --cloud-type=t2.micro \
              --labels=cml-runner

  train-model: # (2) Training of the model 
    needs: deploy-runner
    runs-on: [cml-runner]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Model Training
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml ci
          pip install -r requirements.txt
          python train_model.py

  save_metadata: # (3) Push the metadata to DVC
    steps:
      - name: Save metadata into DVC
        run: python save_metadata.py